### ISSUE TITLE
Welche Git-Lesson?

### ISSUE THREAD

**Issue by katrinleinweber** [evamarik/2018-11-12-cologne#1]
Welche Lernziele sollen die Teilnehmer*innen erreichen? Welches Material kommt infrage? Ich schlage vor, wir sammeln hier :+1:, :-1: & Kommentare, und erstellen anschließend ein PR, das das gewählte Material in

https://github.com/evamarik/2018-11-12-cologne/blob/407114e51193ef7c31974df85156d5210bc04cf0/_includes/lc/schedule.html#L21-L23

verlinkt, mergen es aber erst nach dem WS. Hier schonmal meine Materialvorschläge (Vortrag natürlich jeweils auf Deutsch, oder?):

**Comment by katrinleinweber** [comment]
- [Accessibility Through Git](https://doi.org/10.5446/37825#t=12:15) ([slides](https://docs.google.com/presentation/d/1cMdyHkuvK3bgi3FMP_R9wQJ5qFmoYMR7XAWciHf8H4s/edit#slide=id.g3d673d8e12_0_57); übersetze ich dann noch ins Deutsche)

**Comment by katrinleinweber** [comment]
- https://github.com/caltechlibrary/git-desktop

**Comment by katrinleinweber** [comment]
- https://librarycarpentry.github.io/lc-git/

**Comment by konrad** [comment]
Ich habe persönlich keine Präferenz. Ich bin in vorherigen Workshop von git in der Shell zu GitHub und auch von GitHub zu git in der Shell gegangen. Hat beides seine Vor- und Nachteile und ich konnte keine signifikanten Stärken bei einem der Ansätze sehen. Die Version mit GitHub Desktop würde ich gerne mal ausprobieren (gerade kurz überflogen).

**Comment by katrinleinweber** [comment]
Fürs Archiv: Wir haben letztendlich Atom & GitHub-Desktop gelehrt.
